Resources:
  mangaTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: chapter-${env:PROFILE}-${opt:stage}
      AttributeDefinitions:
        - AttributeName: chapterLink
          AttributeType: S
      KeySchema:
        - AttributeName: chapterLink
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      # GlobalSecondaryIndexes:
      #   - IndexName: slug-index
      #     KeySchema:
      #       - AttributeName: slug
      #         KeyType: HASH
      #     Projection:
      #       ProjectionType: ALL
