Resources:
  postTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: manga-${param:profile}-${opt:stage}
      AttributeDefinitions:
        - AttributeName: mangaId
          AttributeType: S
        - AttributeName: slug
          AttributeType: S
      KeySchema:
        - AttributeName: mangaId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      GlobalSecondaryIndexes:
        - IndexName: slug-index
          KeySchema:
            - AttributeName: slug
              KeyType: HASH
          Projection:
            ProjectionType: ALL
